-- ============================================================
-- Auteur: Olivier Dunn, Maxime Malette, Thomas Paré, Ahmed Hamissi
-- Date de création: 2025-11-24
-- Description:
-- Script postgreSQL de creation du schema GestionImmobilière ainsi que les tables
-- ============================================================
CREATE SCHEMA IF NOT EXISTS Gestion;
DROP TYPE IF EXISTS mois CASCADE;
DROP TYPE IF EXISTS statutTravaux CASCADE;
DROP TYPE IF EXISTS typePaiement CASCADE;
DROP TYPE IF EXISTS statutLogement CASCADE;
DROP TYPE IF EXISTS langueParle CASCADE;


-- Création des types
CREATE TYPE mois AS ENUM ('Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre');
CREATE TYPE statutTravaux AS ENUM  ('Prévu', 'En cours', 'Termine', 'Annule');
CREATE TYPE typePaiement AS ENUM  ('Comptant', 'Chèque','Crédit','Débit', 'Interac');
CREATE TYPE statutLogement AS ENUM ('Vacant','Loué','En réno');
CREATE TYPE langueParle AS ENUM  ('Français','Anglais','Espagnol');


--Création de la table adresses--
CREATE TABLE IF NOT EXISTS Gestion.Adresses
(
	idAdresse		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	noCivique		INTEGER NOT NULL,
	rue				VARCHAR(30) NOT NULL,
	ville			VARCHAR(50) NOT NULL,
	codePostal		CHAR(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS Gestion.Proprietaires
(
	idProprietaire	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idAdresse		INTEGER NOT NULL,
	nbPortesPro		INTEGER	NOT NULL,
	nbImmeublesPro	INTEGER NOT NULL,
	specimenCheq	BYTEA	UNIQUE,
	
	Constraint FK_ProprietaireAdresses
		FOREIGN KEY (idAdresse)
			REFERENCES Gestion.Adresses (idAdresse)
);

CREATE TABLE IF NOT EXISTS Gestion.Compagnies
(
	idProprietaire	INTEGER PRIMARY KEY,
	noTelephone		VARCHAR(10) NOT NULL,
	courriel		VARCHAR(50) NOT NULL,
	nom				VARCHAR(50)	NOT NULL,

	CONSTRAINT FK_CompagnieProprietaire
		FOREIGN KEY (idProprietaire)
			REFERENCES Gestion.Proprietaires (idProprietaire)
);

CREATE TABLE IF NOT EXISTS Gestion.Particuliers
(
	idProprietaire	INTEGER PRIMARY KEY,
	noTelephone		VARCHAR(10) NOT NULL,
	courriel		VARCHAR(50) NOT NULL,
	nom				VARCHAR(50)	NOT NULL,
	prenom			VARCHAR(50) NOT NULL,
			
	CONSTRAINT FK_ParticulierProprietaire
		FOREIGN KEY (idProprietaire)
			REFERENCES Gestion.Proprietaires (idProprietaire)
);

--Création de la table Regles--
CREATE TABLE IF NOT EXISTS Gestion.Regles
(
	idRegle			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fumeur			BOOLEAN NOT NULL DEFAULT FALSE,
	chat			BOOLEAN NOT NULL DEFAULT FALSE,
	chien			BOOLEAN NOT NULL DEFAULT FALSE,
	bbq				BOOLEAN NOT NULL DEFAULT FALSE
);

--Création de la table Inclusions--
CREATE TABLE IF NOT EXISTS Gestion.Inclusions
(
	idInclusion		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	meuble			BOOLEAN NOT NULL DEFAULT FALSE,
	chauffage		BOOLEAN NOT NULL DEFAULT FALSE,
	electricite		BOOLEAN NOT NULL DEFAULT FALSE,
	internet		BOOLEAN NOT NULL DEFAULT FALSE,
	eauChaude		BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Gestion.Travaux
(
	idTravail		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dateDebut		DATE NOT NULL,
	dateFin			DATE,
	coutEstime		NUMERIC(12,2),
	coutFinal		NUMERIC(12,2),
	statut			statutTravaux DEFAULT 'Prévu' NOT NULL,
	description 	VARCHAR(100),
	--Contrainte qui check que chaque dateDebut est avant la date de fin
	CONSTRAINT verif_date_valide_Travaux
				CHECK (dateFin IS NULL OR dateDebut <= dateFin)
);

CREATE TABLE IF NOT EXISTS Gestion.PaiementsTravaux
(
	idPaiementTravail	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idTravail			INTEGER NOT NULL,
	datePaiement		DATE,
	montant				NUMERIC(12,2) NOT NULL,
	modePaiement		typePaiement NOT NULL,
	commentaire			VARCHAR(500),

	CONSTRAINT FK_PaiementTravauxTravaux
		FOREIGN KEY (idTravail)
			REFERENCES Gestion.Travaux (idTravail)
);

CREATE TABLE IF NOT EXISTS Gestion.ContratsGestion
(
	idContrat			INTEGER PRIMARY KEY,
	dateDebut			DATE NOT NULL,
	dateFin				DATE,
	montantMensuel		NUMERIC(12,2) NOT NULL,
	pourcentageGestion	NUMERIC(2,2) NOT NULL,
	prixRelocation		NUMERIC(12,2) NOT NULL,
	clauses				VARCHAR(500),

	CONSTRAINT FK_Compagnie_Proprietaire
        FOREIGN KEY (idContrat)	
            REFERENCES Gestion.Proprietaires(idProprietaire),
	
	CONSTRAINT verif_date_valide_ContratsGestion
				CHECK (dateFin IS NULL OR dateDebut <= dateFin)
);

CREATE TABLE IF NOT EXISTS Gestion.PaimentsGestion
(
	idPaiementGestion 	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idContrat			INTEGER NOT NULL,
	datePaiement		DATE NOT NULL,
	montant				NUMERIC(12,2) NOT NULL,
	modePaiement		typePaiement NOT NULL,
	commentaire			VARCHAR(500),

	CONSTRAINT FK_PaiementGestionContratsGestion
		FOREIGN KEY (idContrat)
			REFERENCES Gestion.ContratsGestion(idContrat)
);
CREATE TABLE IF NOT EXISTS Gestion.Immeubles
(
	idImmeuble		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idAdresse		INTEGER NOT NULL,
	idProprietaire	INTEGER NOT NULL,
	idRegle			INTEGER NOT NULL,
	nbPortes		INTEGER NOT NULL,
	nbStationnement	INTEGER NOT NULL,
	description		VARCHAR(500),

	CONSTRAINT FK_ImmeublesAdresses
		FOREIGN KEY (idAdresse)
			REFERENCES Gestion.Adresses (idAdresse),
			
	CONSTRAINT FK_ImmeublesProprietaires
		FOREIGN KEY (idProprietaire)
			REFERENCES Gestion.Proprietaires (idProprietaire),
	
	CONSTRAINT FK_ImmeublesRegles
		FOREIGN KEY (idRegle)
			REFERENCES Gestion.Regles (idRegle)
);


CREATE TABLE IF NOT EXISTS Gestion.TravauxImmeuble
(
	idImmeuble		INTEGER NOT NULL,
	idTravail		INTEGER NOT NULL,
	
	CONSTRAINT PK_TravauxImmeubles
		PRIMARY KEY (idImmeuble,idTravail),
		
	CONSTRAINT FK_TravauxImmeublesImmeubles
		FOREIGN KEY (idImmeuble)
			REFERENCES Gestion.Immeubles (idImmeuble),
	
	CONSTRAINT FK_TravauxImmeublesTravail
		FOREIGN KEY (idTravail)
			REFERENCES Gestion.Travaux (idTravail)
);

CREATE TABLE IF NOT EXISTS Gestion.Logements
(
	idLogement		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idImmeuble		INTEGER NOT NULL,
	idInclusion		INTEGER NOT NULL,
	nbPieces		INTEGER NOT NULL,
	balcon			BOOLEAN NOT NULL DEFAULT FALSE,
	statut			statutLogement NOT NULL DEFAULT 'Loué',
	noPorte			INTEGER NOT NULL,
	description		VARCHAR(500),

	CONSTRAINT FK_LogementsImmeubles
		FOREIGN KEY (idImmeuble)
			REFERENCES Gestion.Immeubles (idImmeuble),
			
	CONSTRAINT FK_LogementsInclusions
		FOREIGN KEY (idInclusion)
			REFERENCES Gestion.Inclusions (idInclusion)	
);

CREATE TABLE IF NOT EXISTS Gestion.TravauxLogement
(
	idLogement		INTEGER NOT NULL,
	idTravail		INTEGER NOT NULL,
	
	CONSTRAINT PK_TravauxLogement
		PRIMARY KEY (idLogement,idTravail),
		
	CONSTRAINT FK_TravauxLogementsLogements
		FOREIGN KEY (idLogement)
			REFERENCES Gestion.Logements (idLogement),
	
	CONSTRAINT FK_TravauxLogementsTravaux
		FOREIGN KEY (idTravail)
			REFERENCES Gestion.Travaux (idTravail)
);
CREATE TABLE IF NOT EXISTS Gestion.Locataires
(
	idLocataire		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idLogement		INTEGER NOT NULL,
	langue			langueParle NOT NULL DEFAULT 'Français',
	noTelephone		VARCHAR(10) NOT NULL,
	prenom			VARCHAR(30) NOT NULL,
	nom				VARCHAR(30) NOT NULL,
	courriel		VARCHAR(50) NOT NULL,
	modePaiement	typePaiement NOT NULL,
	solde			NUMERIC(10,2),
	
	
	
	CONSTRAINT FK_LocatairesLogement
			FOREIGN KEY (idLogement)
				REFERENCES Gestion.Logements (idLogement)

);

CREATE TABLE IF NOT EXISTS Gestion.Baux
(
	idBail			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idLocataire		INTEGER NOT NULL,
	dateDebut		DATE NOT NULL,
	dateFin			DATE NOT NULL,
	loyer			NUMERIC(10,2) NOT NULL,
		
		CONSTRAINT FK_BailLocataires 
			FOREIGN KEY (idLocataire)
				REFERENCES Gestion.Locataires (idLocataire),
			
				
	CONSTRAINT verif_date_valide_Baux
		CHECK (dateFin IS NULL OR dateDebut <= dateFin)
);



CREATE TABLE IF NOT EXISTS Gestion.PaiementsLocataire
(
	idPaiementsLocataire	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	idLocataire				INTEGER NOT NULL,
	datePaiement			DATE,
	montant					NUMERIC(10,2) NOT NULL,
	periode					mois NOT NULL,
	commentaire				VARCHAR(500),

	CONSTRAINT FK_PaiementsLocataireLocataires
		FOREIGN KEY (idLocataire)
			REFERENCES Gestion.Locataires (idLocataire)
);


